# Generated by Django 3.1 on 2020-08-09 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True)),
                ('data_categoria', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=50, unique=True)),
                ('ingredientes', models.TextField(max_length=500)),
                ('modo_preparo', models.TextField(max_length=2000)),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.TextField(max_length=100)),
                ('data_receita', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.categoria')),
            ],
        ),
    ]
