# Generated by Django 3.1 on 2020-08-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(max_length=50),
        ),
    ]
